# Generated by Django 4.0.3 on 2022-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='string',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='string',
            name='updated',
        ),
        migrations.AddField(
            model_name='string',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
