# Generated by Django 4.0.3 on 2022-03-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_string_options_remove_string_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='string',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
