# Generated by Django 4.0.3 on 2022-03-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritestring',
            name='strings',
        ),
        migrations.AddField(
            model_name='favoritestring',
            name='strings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.string'),
        ),
        migrations.AlterField(
            model_name='favoritestring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
