# Generated by Django 4.0.3 on 2022-03-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_strings_favoritestring_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritestring',
            name='string',
        ),
        migrations.AddField(
            model_name='favoritestring',
            name='string',
            field=models.ManyToManyField(to='main.string'),
        ),
        migrations.AlterField(
            model_name='favoritestring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
