# Generated by Django 4.0.3 on 2022-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_favoritestring_string_favoritestring_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='main.user'),
        ),
    ]
