# Generated by Django 4.0.3 on 2022-03-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_string_favorite_string_favored_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
